# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nfc_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
